lint:
  files_unchanged:
    - Dockerfile

  files_exist:
    - igenomes.config
    - modules/local/get_software_versions.nf
    - Dockerfile

  schema_params:
    - input
actions_awsfulltest: False
pipeline_todos: False
actions_ci: False
repository_type: pipeline
